spring:
  h2:
    console:
      enabled: true

# local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sprboottest@gmail.com
    password: alsrb110
    properties:
      mail:
        protocol: smtps
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

